import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
  container: {
    position: 'relative',
    marginLeft: 10,
    marginVertical: 10,
    width: 150,
    paddingBottom: 7,
    borderRadius: 13,
    backgroundColor: '$white',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
  banner: {
    width: 150,
    height: 150,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    backgroundColor: '#fff',
  },
  name: {
    color: '$black',
    fontSize: '$normalText',
    fontWeight: '$fontWeightNormal',
    paddingHorizontal: 5,
    paddingTop: 5,
    textTransform: 'uppercase',
  },
  textDiscount: {
    color: '$txtFocusInput',
    fontSize: '$normalText',
    fontWeight: '$fontWeightBold',
    lineHeight: '$mediumLineHeight',
  },
  viewSeparated: {
    width: 2,
    height: 17,
    backgroundColor: '$txtFocusInput',
    marginHorizontal: 7,
    alignSelf: 'center',
  },
  textMoneyOrigin: {
    paddingTop: 4,
    fontWeight: '$fontWeightNormal',
    paddingHorizontal: 1,
    color: '$btnColorBlack',
    fontSize: '$smallText10',
    textAlign: 'center',
  },
  centerTextMoney: {
    height: 1,
    width: '100%',
    backgroundColor: '$btnBorderColor',
    position: 'absolute',
    alignSelf: 'center',
    top: '50%',
  },
  wrapPrice: {
    padding: 5,
    flexDirection: 'row',
  },
  btnBuy: {
    backgroundColor: '$txtFocusInput',
    marginHorizontal: 5,
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: 8,
    borderRadius: 5,
  },
  textBuy: {
    color: '$white',
    fontSize: '$normalText',
    lineHeight: '$normalLineHeight',
  },
  badge: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: 25,
    minWidth: '50%',
    borderTopLeftRadius: 10,
    backgroundColor: '$btnRed',
    opacity: 0.8,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 10,
  },
  badgeText: {
    color: '$white',
    fontWeight: '$fontWeightBold',
    fontSize: '$normalText',
    textAlign: 'center',
  },
});
