import {Platform} from 'react-native';
import EStyleSheet from 'react-native-extended-stylesheet';

export default EStyleSheet.create({
  wrap: {
    backgroundColor: '#FFD8BB',
    marginVertical: 15,
  },
  wrapFlashSale: {
    top: -17,
    left: 0,
    flexDirection: 'row',
    alignItems: 'center',
  },
  wrapTimer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 10,
  },
  textTimer: {
    fontSize: '$mediumText',
    borderRadius: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: 'black',
    color: '$white',
  },
  colon: {
    fontSize: 25,
    color: 'black',
    paddingBottom: 5,
  },
  itemWrap: {
    flexDirection: 'row',
    borderRadius: 10,
    marginBottom: 15,
    marginHorizontal: 10,
    backgroundColor: '$white',
    shadowColor: '$shadow',
    shadowOffset: {
      width: 1,
      height: 1,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 2,
  },
  image: {
    width: 125,
    height: 125,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  wrapContent: {
    flex: 1,
    paddingLeft: 16,
    justifyContent: 'space-between',
    paddingVertical: 10,
    paddingRight: 9,
  },
  name: {
    fontSize: '$mediumText',
    fontWeight: '$fontWeightBold',
    color: '$btnColorBlack',
  },
  wrapBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textDiscount: {
    color: '$txtFocusInput',
    fontSize: '$mediumText',
    lineHeight: 23,
    fontWeight: '$fontWeightBold',
  },
  viewSeparated: {
    width: 2,
    height: 17,
    backgroundColor: '$txtFocusInput',
    marginHorizontal: 7,
    alignSelf: 'center',
  },
  textMoneyOrigin: {
    paddingTop: 4,
    fontWeight: '$fontWeightBold',
    color: '$btnColorBlack',
    paddingHorizontal: 1,
  },
  centerTextMoney: {
    height: 1,
    width: '100%',
    backgroundColor: '$black',
    position: 'absolute',
    alignSelf: 'center',
    top: '50%',
    marginTop: Platform.select({
      android: 2,
      ios: 0,
    }),
  },
  wrapPrice: {
    paddingTop: 10,
    flexDirection: 'row',
  },
  wrapViewDisCount: {
    width: 61,
    height: 21,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#FF5728',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  wrapTextDisCount: {
    color: '#FF5728',
    padding: 3,
    fontSize: '$smallText',
    lineHeight: 14,
  },
  wrapSold: {
    flex: 1,
    height: 15,
    backgroundColor: '#80CD28',
    borderRadius: 8,
  },
  soldLine: {
    position: 'absolute',
    backgroundColor: '#FF5728',
    height: 15,
    borderRadius: 8,
  },
  wrapSoldText: {
    fontSize: '$smallText',
    alignSelf: 'center',
    justifyContent: 'center',
    color: '$white',
  },
  btnBuy: {
    width: 61,
    height: 26,
    marginLeft: 10,
    borderRadius: 5,
    backgroundColor: '#80CD28',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnBuyOff: {
    width: 61,
    height: 26,
    marginLeft: 10,
    borderRadius: 5,
    backgroundColor: '#BDBDBD',
    justifyContent: 'center',
    alignItems: 'center',
  },
  buyText: {
    fontWeight: '$fontWeightBold',
    color: '$white',
  },
});
