import EStyleSheet from 'react-native-extended-stylesheet';
import {getBottomSpace} from 'react-native-iphone-x-helper';

export default EStyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '$white',
  },
  header: {
    borderBottomWidth: 2,
    borderColor: '$contentLoaderBackgroundColor',
    paddingBottom: 5,
  },
  contentContainerStyle: {
    paddingBottom: 71 + getBottomSpace(),
  },
  viewSeparated: {
    height: 1,
    backgroundColor: '$btnBorderColor',
  },
  wrapSelect: {
    paddingHorizontal: 16,
    paddingBottom: 22,
  },
  titleSelect: {
    fontSize: '$titleSelect',
    lineHeight: 18,
    fontWeight: '$fontWeightBold',
    marginTop: 20,
    color: '$btnColorBlack',
    fontStyle: 'normal',
  },
  btnSelect: {
    height: 44,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '$txtFocusInput',
    backgroundColor: '$activeCardBackground',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
    flexDirection: 'row',
    paddingHorizontal: 15,
  },
  textSelect: {
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '$fontWeightBold',
    color: '$btnColorBlack',
  },
  textSelect2: {
    color: '$btnRed',
    marginTop: 20,
    fontStyle: 'italic',
  },
  textSelect3: {
    color: '$btnRed',
    fontStyle: 'italic',
  },
  wrapBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    // height: 61 + getBottomSpace(),
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 8,

    backgroundColor: '$white',
    paddingTop: 10,
    paddingBottom: 10 + getBottomSpace() / 2,
  },
  btnSelect2: {
    backgroundColor: '$replyBackgroundRed',
    borderColor: '$btnRed',
  },
  btnTakeOrder: {
    flex: 1,
    height: 41,
    borderRadius: 10,
    backgroundColor: '#FF5728',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 2,
  },
  textBtnTakeOrder: {
    fontSize: '$normalText16',
    lineHeight: 18,
    fontWeight: '$fontWeightBold',
    color: '$white',
  },
  btnAddProduct: {
    flex: 1,
    backgroundColor: '$txtFocusInput',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    height: 41,
  },
  wrapOrderItem: {
    flexDirection: 'row',
    marginTop: 20,
    width: '100%',
  },
  amount: {
    width: 46,
    height: 29,
    borderRadius: 10,
    backgroundColor: '$txtFocusInput',
    justifyContent: 'center',
    alignItems: 'center',
  },
  textAmount: {
    color: '$white',
    fontSize: '$mediumText',
    lineHeight: 22,
  },
  wrapRight: {
    marginLeft: 5,
    flex: 1,
  },
  wrapName: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  name: {
    fontSize: '$mediumText',
    lineHeight: 21,
    flex: 1,
    color: '$black',
  },
  money: {
    fontSize: '$mediumText',
    lineHeight: 21,
    marginRight: 10,
    color: '$btnColorBlack',
  },
  wrapNote: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  note: {
    flex: 1,
    fontSize: '$mediumText',
    lineHeight: 21,
    fontStyle: 'italic',
    color: '$btnBorderColor',
    paddingRight: 5,
  },
  wrapBtnAddSub: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 118,
    height: 28,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: '$btnBorderColor',
  },
  btnSub: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
  wrapAmountBtn: {
    flex: 1,
    textAlign: 'center',
    color: '$btnColorBlack',
    fontSize: '$mediumText',
  },
  separatedBtn: {
    $btnBorderColor: '#BDBDBD',
    height: '100%',
    width: 1,
    backgroundColor: '$btnBorderColor',
    lineHeight: 21,
  },
  topping: {
    color: '$replyTextRed',
    fontSize: '$mediumText',
    lineHeight: 21,
    paddingTop: 10,
  },
  buttonLabel: {
    color: '$btnColorBlack',
  },
  desRight: {
    color: '$btnRed',
  },

  wrapDeliveryOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 20,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 0.8,
    borderColor: '$black',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  childCheckBox: {
    width: 14,
    height: 14,
    backgroundColor: '$txtFocusInput',
    borderRadius: 7,
  },
  nameDeliveryOption: {
    flex: 1,
    paddingHorizontal: 14,
    fontSize: '$mediumText',
    lineHeight: 21,
    color: '$black',
  },
  textBlack: {
    color: '$btnColorBlack',
  },
  textPrimary: {
    color: '$txtFocusInput',
    fontWeight: '$fontWeightBold',
  },
  textRed: {
    color: '$btnRed',
    fontWeight: '$fontWeightBold',
  },
  wrapTitle: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  desBottom: {
    paddingHorizontal: 16,
    paddingVertical: 20,
    color: '$black',
    fontSize: '$titleSelect',
    lineHeight: 19,
  },
});
