export default {
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  UPDATE_ITEM_TO_CART: 'UPDATE_ITEM_TO_CART',
  DELETE_ITEM_TO_CART: 'DELETE_ITEM_TO_CART',
  SET_SELECTED_BRANCH: 'SET_SELECTED_BRANCH',
  SET_SELECTED_ADDRESS: 'SET_SELECTED_ADDRESS',
  SET_SELECTED_VOUCHER: 'SET_SELECTED_VOUCHER',
  RESET_CART: 'RESET_CART',
};
